[package]
name = "pure_component"
version = "0.1.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced = { path = "../../..", features = ["pure"] }
iced_native = { path = "../../../native" }
iced_lazy = { path = "../../../lazy" }
iced_pure = { path = "../../../pure" }
